version: '3'

services:
    crm-api.thermas.app:
        build:
            dockerfile: docker/Dockerfile
            context: .
        image: '${IMAGE_TAG:-crm-api-thermas}'
        container_name: 'crm-api-thermas'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            XDEBUG_MODE: '${XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${XDEBUG_CONFIG:-client_host=host.docker.internal}'
            BUILD_ENV: '${APP_ENV:-local}'
        volumes:
            - '.:/var/www/html'
        networks:
            - thermas
        depends_on:
            - mysql8.0
    mysql8.0:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 0
        volumes:
            - 'thermas-mysql:/var/lib/mysql'
        networks:
            - thermas
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
networks:
    thermas:
        driver: bridge
volumes:
    thermas-mysql:
        driver: local
